production:
  clients:
    default:
      uri: ENV['MLAB_URI']
development:
  clients:
    default:
      database: last_stop_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: last_stop_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
